---
- name: Create prometheus group
  group:
    name: prometheus
    system: true
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    create_home: false
    state: present

- block:
    - name: Install prometheus node_exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ curr_arch }}.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: propagate binaries
      copy:
        src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ curr_arch }}/node_exporter"
        dest: "{{ prometheus_node_exporter_binary_install_dir }}"
        mode: 0755
        owner: prometheus
        group: prometheus
        remote_src: yes
      notify:
        - restart node_exporter
  when:
  - not prometheus_node_exporter_skip_install

- name: Delete prometheus node_exporter tmp folder
  file:
    path: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ curr_arch }}"
    state: absent
  when:
    - not prometheus_node_exporter_skip_install

- name: Copy systemd init file and start node_exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node_exporter