---
- name: Get latest release
  uri:
    url: "https://api.github.com/repos/prometheus/prometheus/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    validate_certs: false
  register: last_release
  until: last_release.status == 200
  retries: 5

- name: "Set prometheus version to {{ last_release.json.tag_name[1:] }}"
  set_fact:
    prometheus_version: "{{ last_release.json.tag_name[1:] }}"
  when:
  - prometheus_version == "latest"
  - not prometheus_skip_install

- name: Create prometheus group
  group:
    name: prometheus
    system: true
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    create_home: false
    home: "{{ prometheus_db_dir }}"
    state: present

- name: Create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0770
  loop:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

- block:
    - name: Install prometheus
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ curr_arch }}.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: propagate binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ curr_arch }}/prometheus"
        dest: "{{ prometheus_binary_install_dir }}"
        mode: 0755
        owner: prometheus
        group: prometheus
        remote_src: yes
      notify:
        - restart prometheus
  when:
    - not prometheus_skip_install
  

- name: Delete prometheus tmp folder
  file:
    path: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ curr_arch }}"
    state: absent
  when:
    - not prometheus_skip_install

- name: Copy systemd init file and start prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus
